name: science_dex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:



   fonts:
     - family: Inter
       fonts:
         - asset: fonts/Inter-Black.ttf
         - asset: fonts/Inter-Bold.ttf
         - asset: fonts/Inter-ExtraBold.ttf
         - asset: fonts/Inter-ExtraLight.ttf
         - asset: fonts/Inter-Light.ttf
         - asset: fonts/Inter-Medium.ttf
         - asset: fonts/Inter-Regular.ttf
         - asset: fonts/Inter-SemiBold.ttf
         - asset: fonts/Inter-Thin.ttf

   uses-material-design: true
